-- Creating ICDB User -------------

DROP TABLESPACE ICDB_DATA INCLUDING CONTENTS AND DATAFILES;

CREATE TABLESPACE ICDB_DATA DATAFILE 
  'D:\oraclexe\app\oracle\oradata\XE\ICDB\ICDB_DATA' SIZE 2048M AUTOEXTEND ON NEXT 50M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


DROP TABLESPACE ICDB_TMP INCLUDING CONTENTS AND DATAFILES;

CREATE TEMPORARY TABLESPACE ICDB_TMP TEMPFILE 
  'D:\oraclexe\app\oracle\oradata\XE\ICDB\ICDB_TMP' SIZE 500M AUTOEXTEND ON NEXT 50M MAXSIZE UNLIMITED
TABLESPACE GROUP ''
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1M;

DROP USER ICDB CASCADE;

CREATE USER ICDB
  IDENTIFIED BY 123
  DEFAULT TABLESPACE ICDB_DATA
  TEMPORARY TABLESPACE ICDB_TMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 3 Roles  
  GRANT CONNECT TO ICDB WITH ADMIN OPTION;
  GRANT RESOURCE TO ICDB WITH ADMIN OPTION;
  GRANT DBA TO ICDB WITH ADMIN OPTION;
  ALTER USER ICDB DEFAULT ROLE ALL;
  -- 2 System Privileges  
  GRANT ALTER TABLESPACE TO ICDB WITH ADMIN OPTION;
  GRANT UNLIMITED TABLESPACE TO ICDB WITH ADMIN OPTION;

  -------------Creating Support User ----------------

DROP TABLESPACE SUPPORT_DATA INCLUDING CONTENTS AND DATAFILES;

CREATE TABLESPACE SUPPORT_DATA DATAFILE 
  'D:\oraclexe\app\oracle\oradata\XE\SUPPORT\SUPPORT_DATA' SIZE 2048M AUTOEXTEND ON NEXT 50M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


DROP TABLESPACE SUPPORT_TMP INCLUDING CONTENTS AND DATAFILES;

CREATE TEMPORARY TABLESPACE SUPPORT_TMP TEMPFILE 
  'D:\oraclexe\app\oracle\oradata\XE\SUPPORT\SUPPORT_TMP' SIZE 500M AUTOEXTEND ON NEXT 50M MAXSIZE UNLIMITED
TABLESPACE GROUP ''
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1M;


DROP USER SUPPORT CASCADE;

CREATE USER SUPPORT
  IDENTIFIED BY 123
  DEFAULT TABLESPACE SUPPORT_DATA
  TEMPORARY TABLESPACE SUPPORT_TMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 3 Roles  
  GRANT CONNECT TO SUPPORT WITH ADMIN OPTION;
  GRANT RESOURCE TO SUPPORT WITH ADMIN OPTION;
  GRANT DBA TO SUPPORT WITH ADMIN OPTION;
  ALTER USER SUPPORT DEFAULT ROLE ALL;
  -- 2 System Privileges  
  GRANT ALTER TABLESPACE TO SUPPORT WITH ADMIN OPTION;
  GRANT UNLIMITED TABLESPACE TO SUPPORT WITH ADMIN OPTION;
  
    -------------Creating JCCS User ----------------

DROP TABLESPACE JCCS_DATA INCLUDING CONTENTS AND DATAFILES;

CREATE TABLESPACE JCCS_DATA DATAFILE 
  'D:\oraclexe\app\oracle\oradata\XE\JCCS\JCCS_DATA' SIZE 2048M AUTOEXTEND ON NEXT 50M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

DROP TABLESPACE JCCS_TMP INCLUDING CONTENTS AND DATAFILES;

CREATE TEMPORARY TABLESPACE JCCS_TMP TEMPFILE 
  'D:\oraclexe\app\oracle\oradata\XE\JCCS\JCCS_TMP' SIZE 500M AUTOEXTEND ON NEXT 50M MAXSIZE UNLIMITED
TABLESPACE GROUP ''
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1M;


DROP USER JCCS CASCADE;

CREATE USER JCCS
  IDENTIFIED BY 123
  DEFAULT TABLESPACE JCCS_DATA
  TEMPORARY TABLESPACE JCCS_TMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 3 Roles  
  GRANT CONNECT TO JCCS WITH ADMIN OPTION;
  GRANT RESOURCE TO JCCS WITH ADMIN OPTION;
  GRANT DBA TO JCCS WITH ADMIN OPTION;
  ALTER USER JCCS DEFAULT ROLE ALL;
  -- 2 System Privileges  
  GRANT ALTER TABLESPACE TO JCCS WITH ADMIN OPTION;
  GRANT UNLIMITED TABLESPACE TO JCCS WITH ADMIN OPTION;
  
      -------------Creating MOEP User ----------------

DROP TABLESPACE MOEP_DATA INCLUDING CONTENTS AND DATAFILES;

CREATE TABLESPACE MOEP_DATA DATAFILE 
  'D:\oraclexe\app\oracle\oradata\XE\MOEP\MOEP_DATA' SIZE 2048M AUTOEXTEND ON NEXT 50M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

DROP TABLESPACE MOEP_TMP INCLUDING CONTENTS AND DATAFILES;

CREATE TEMPORARY TABLESPACE MOEP_TMP TEMPFILE 
  'D:\oraclexe\app\oracle\oradata\XE\MOEP\MOEP_TMP' SIZE 500M AUTOEXTEND ON NEXT 50M MAXSIZE UNLIMITED
TABLESPACE GROUP ''
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1M;


DROP USER MOEP CASCADE;

CREATE USER MOEP
  IDENTIFIED BY 123
  DEFAULT TABLESPACE MOEP_DATA
  TEMPORARY TABLESPACE MOEP_TMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 3 Roles  
  GRANT CONNECT TO MOEP WITH ADMIN OPTION;
  GRANT RESOURCE TO MOEP WITH ADMIN OPTION;
  GRANT DBA TO MOEP WITH ADMIN OPTION;
  ALTER USER MOEP DEFAULT ROLE ALL;
  -- 2 System Privileges  
  GRANT ALTER TABLESPACE TO MOEP WITH ADMIN OPTION;
  GRANT UNLIMITED TABLESPACE TO MOEP WITH ADMIN OPTION;