gcloud compute instances create-with-container instance-20240723-163041 \
--project=moj-prod-apigee \ 
--zone=us-central1-c \
--machine-type=e2-medium \ 
--network-interface=network-tier=PREMIUM,stack-type=IPV4_ONLY,subnet=default \
--maintenance-policy=MIGRATE \
--provisioning-model=STANDARD \
--service-account=598074804327-compute@developer.gserviceaccount.com \
--scopes=https://www.googleapis.com/auth/devstorage.read_only,https://www.googleapis.com/auth/logging.write,https://www.googleapis.com/auth/monitoring.write,https://www.googleapis.com/auth/service.management.readonly,https://www.googleapis.com/auth/servicecontrol,https://www.googleapis.com/auth/trace.append \
--image=projects/cos-cloud/global/images/cos-stable-113-18244-85-64 \
--boot-disk-size=50GB \
--boot-disk-type=pd-balanced \
--boot-disk-device-name=instance-20240723-163041 \
--container-image=shawkyfoda/smarttooldb-image:latest \
--container-restart-policy=on-failure \
--container-arg=-p\ 1521:1521 \ 
--no-shielded-secure-boot \
--shielded-vtpm \
--shielded-integrity-monitoring \
--labels=goog-ec-src=vm_add-gcloud,container-vm=cos-stable-113-18244-85-64