export _app_path=/opt/tomcat/webapps/SmartTool 
export _libPath="${_app_path}/WEB-INF/lib" 


export _CP="${_app_path}/WEB-INF/classes;"
# New Dynamic Methos to Build the Class Path 
export _CP="${_CP}$(JARS=("$_libPath"/*.jar); IFS=:; echo "${JARS[*]}")"

# Old MAnual Method 
#  export _CP="${_CP}${_app_path}/WEB-INF/lib/implex-core.jar;"
#  export _CP="$_CP$_app_path/WEB-INF/lib/side-sas.jar;"
#  export _CP="$_CP$_app_path/WEB-INF/lib/side-swaf.jar;"
#  export _CP="$_CP$_app_path/WEB-INF/lib/servlet-api.jar;"
#  export _CP="$_CP$_app_path/WEB-INF/lib/BC4J;"
#  export _CP="$_CP$_app_path/WEB-INF/lib/bc4jhtml.jar;"
#  export _CP="$_CP$_app_path/WEB-INF/lib/bc4juixtags.jar;"
#  export _CP="$_CP$_app_path/WEB-INF/lib/bc4j_jclient_common.jar;"
#  export _CP="$_CP$_app_path/WEB-INF/lib/cayenne.jar;"
#  export _CP="$_CP$_app_path/WEB-INF/lib/clrt.jar;"
#  export _CP="$_CP$_app_path/WEB-INF/lib/common;"
#  export _CP="$_CP$_app_path/WEB-INF/lib/commons-collections-3.1.jar;"
#  export _CP="$_CP$_app_path/WEB-INF/lib/commons-configuration-1.2.jar;"
#  export _CP="$_CP$_app_path/WEB-INF/lib/commons-lang-2.1.jar;"
#  export _CP="$_CP$_app_path/WEB-INF/lib/commons-logging.jar;"
#  export _CP="$_CP$_app_path/WEB-INF/lib/Concurrent.jar;"
#  export _CP="$_CP$_app_path/WEB-INF/lib/CrystalContentModels.jar;"
#  export _CP="$_CP$_app_path/WEB-INF/lib/CrystalDatabaseConnectors.jar;"
#  export _CP="$_CP$_app_path/WEB-INF/lib/Crystal#  exporters.jar;"
#  export _CP="$_CP$_app_path/WEB-INF/lib/Crystal#  exportingBase.jar;"
#  export _CP="$_CP$_app_path/WEB-INF/lib/CrystalFormulas.jar;"
#  export _CP="$_CP$_app_path/WEB-INF/lib/CrystalQueryEngine.jar;"
#  export _CP="$_CP$_app_path/WEB-INF/lib/CrystalReportEngine.jar;"
#  export _CP="$_CP$_app_path/WEB-INF/lib/CrystalReportingCommon.jar;"
#  export _CP="$_CP$_app_path/WEB-INF/lib/datatags.jar;"
#  export _CP="$_CP$_app_path/WEB-INF/lib/dsn.jar;"
#  export _CP="$_CP$_app_path/WEB-INF/lib/fileaccess.jar;"
#  export _CP="$_CP$_app_path/WEB-INF/lib/FTP;"
#  export _CP="$_CP$_app_path/WEB-INF/lib/icu4j.jar;"
#  export _CP="$_CP$_app_path/WEB-INF/lib/imap.jar;"
#  export _CP="$_CP$_app_path/WEB-INF/lib/inetfactory.jar;"
#  export _CP="$_CP$_app_path/WEB-INF/lib/J2EE;"
#  export _CP="$_CP$_app_path/WEB-INF/lib/jas.jar;"
#  export _CP="$_CP$_app_path/WEB-INF/lib/jrcadapter.jar;"
#  export _CP="$_CP$_app_path/WEB-INF/lib/jrcerom.jar;"
#  export _CP="$_CP$_app_path/WEB-INF/lib/JSP_RunTime;"
#  export _CP="$_CP$_app_path/WEB-INF/lib/jtds-1.2.jar;"
#  export _CP="$_CP$_app_path/WEB-INF/lib/jug.jar;"
#  export _CP="$_CP$_app_path/WEB-INF/lib/jxl;"
#  export _CP="$_CP$_app_path/WEB-INF/lib/keycodeDecoder.jar;"
#  export _CP="$_CP$_app_path/WEB-INF/lib/log4j.jar;"
#  export _CP="$_CP$_app_path/WEB-INF/lib/mailapi.jar;"
#  export _CP="$_CP$_app_path/WEB-INF/lib/MetafileRenderer.jar;"
#  export _CP="$_CP$_app_path/WEB-INF/lib/nls_charset12.jar;"
#  export _CP="$_CP$_app_path/WEB-INF/lib/oc4j.jar;"
#  export _CP="$_CP$_app_path/WEB-INF/lib/ojc.jar;"
#  export _CP="$_CP$_app_path/WEB-INF/lib/ojdbc6.jar;"
#  export _CP="$_CP$_app_path/WEB-INF/lib/ojsp.jar;"
#  export _CP="$_CP$_app_path/WEB-INF/lib/ojsputil.jar;"
#  export _CP="$_CP$_app_path/WEB-INF/lib/Oracle_JDBC;"
#  export _CP="$_CP$_app_path/WEB-INF/lib/Oracle_XML;"
#  export _CP="$_CP$_app_path/WEB-INF/lib/pop3.jar;"
#  export _CP="$_CP$_app_path/WEB-INF/lib/rasapp.jar;"
#  export _CP="$_CP$_app_path/WEB-INF/lib/rascore.jar;"
#  export _CP="$_CP$_app_path/WEB-INF/lib/ReportPrinter.jar;"
#  export _CP="$_CP$_app_path/WEB-INF/lib/rpoifs.jar;"
#  export _CP="$_CP$_app_path/WEB-INF/lib/serialization.jar;"
#  export _CP="$_CP$_app_path/WEB-INF/lib/sftp.jar;"
#  export _CP="$_CP$_app_path/WEB-INF/lib/smtp.jar;"
#  export _CP="$_CP$_app_path/WEB-INF/lib/sqljdbc.jar;"
#  export _CP="$_CP$_app_path/WEB-INF/lib/sqljdbc1.2.jar;"
#  export _CP="$_CP$_app_path/WEB-INF/lib/sqltaglib.jar;"
#  export _CP="$_CP$_app_path/WEB-INF/lib/struts.jar;"
#  export _CP="$_CP$_app_path/WEB-INF/lib/Telnet/inetfactory.jar";
#  export _CP="$_CP$_app_path/WEB-INF/lib/utiltaglib.jar;"
#  export _CP="$_CP$_app_path/WEB-INF/lib/WMParsers;"
#  export _CP="$_CP$_app_path/WEB-INF/lib/xercesImpl.jar;"
#  export _CP="$_CP$_app_path/WEB-INF/lib/xml-apis.jar;"
#  export _CP="$_CP$_app_path/WEB-INF/lib/xmlcomp.jar;"
#  export _CP="$_CP$_app_path/WEB-INF/lib/xmlparserv2.jar;"
#  export _CP="$_CP$_app_path/WEB-INF/lib/jsf-api-1.2_12.jar

export _OPT="-Djbo.maxpoolsize=2 -Djbo.poolrequesttimeout=10000 -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=1100 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dfile.encoding=Windows-1256"
