ALTER SESSION SET CONTAINER = SVDB;

DROP TABLESPACE PNU_DATA INCLUDING CONTENTS AND DATAFILES;

CREATE TABLESPACE PNU_DATA DATAFILE '/opt/oracle/oradata/FREE/SVDB/PNU_DATA.dbf' SIZE 512M AUTOEXTEND ON NEXT 50M MAXSIZE UNLIMITED
LOGGING ONLINE PERMANENT EXTENT MANAGEMENT LOCAL AUTOALLOCATE 
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


DROP TABLESPACE PNU_TMP INCLUDING CONTENTS AND DATAFILES;

CREATE TEMPORARY TABLESPACE PNU_TMP TEMPFILE 
  '/opt/oracle/oradata/FREE/SVDB/PNU_TMP.dbf' SIZE 128M AUTOEXTEND ON NEXT 50M MAXSIZE UNLIMITED
TABLESPACE GROUP ''
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1M;


DROP USER PNU CASCADE;

CREATE USER PNU
  IDENTIFIED BY 123
  DEFAULT TABLESPACE PNU_DATA
  TEMPORARY TABLESPACE PNU_TMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 3 Roles  
  GRANT CONNECT TO PNU WITH ADMIN OPTION;
  GRANT RESOURCE TO PNU WITH ADMIN OPTION;
  GRANT DBA TO PNU WITH ADMIN OPTION;
  ALTER USER PNU DEFAULT ROLE ALL;
  -- 2 System Privileges  
  GRANT ALTER TABLESPACE TO PNU WITH ADMIN OPTION;
  GRANT UNLIMITED TABLESPACE TO PNU WITH ADMIN OPTION;
