ALTER SESSION SET CONTAINER = SVDB;

DROP TABLESPACE JCCS_DATA INCLUDING CONTENTS AND DATAFILES;

CREATE TABLESPACE JCCS_DATA DATAFILE '/opt/oracle/oradata/FREE/SVDB/JCCS_DATA.dbf' SIZE 512M AUTOEXTEND ON NEXT 50M MAXSIZE UNLIMITED
LOGGING ONLINE PERMANENT EXTENT MANAGEMENT LOCAL AUTOALLOCATE 
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


DROP TABLESPACE JCCS_TMP INCLUDING CONTENTS AND DATAFILES;

CREATE TEMPORARY TABLESPACE JCCS_TMP TEMPFILE 
  '/opt/oracle/oradata/FREE/SVDB/JCCS_TMP.dbf' SIZE 128M AUTOEXTEND ON NEXT 50M MAXSIZE UNLIMITED
TABLESPACE GROUP ''
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1M;


DROP USER JCCS CASCADE;

CREATE USER JCCS
  IDENTIFIED BY 123
  DEFAULT TABLESPACE JCCS_DATA
  TEMPORARY TABLESPACE JCCS_TMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 3 Roles  
  GRANT CONNECT TO JCCS WITH ADMIN OPTION;
  GRANT RESOURCE TO JCCS WITH ADMIN OPTION;
  GRANT DBA TO JCCS WITH ADMIN OPTION;
  ALTER USER JCCS DEFAULT ROLE ALL;
  -- 2 System Privileges  
  GRANT ALTER TABLESPACE TO JCCS WITH ADMIN OPTION;
  GRANT UNLIMITED TABLESPACE TO JCCS WITH ADMIN OPTION;
