ALTER SESSION SET CONTAINER = SVDB;

DROP TABLESPACE Support_DATA INCLUDING CONTENTS AND DATAFILES;

CREATE TABLESPACE Support_DATA DATAFILE '/opt/oracle/oradata/FREE/SVDB/Support_DATA.dbf' SIZE 512M AUTOEXTEND ON NEXT 50M MAXSIZE UNLIMITED
LOGGING ONLINE PERMANENT EXTENT MANAGEMENT LOCAL AUTOALLOCATE 
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


DROP TABLESPACE Support_TMP INCLUDING CONTENTS AND DATAFILES;

CREATE TEMPORARY TABLESPACE Support_TMP TEMPFILE 
  '/opt/oracle/oradata/FREE/SVDB/Support_TMP.dbf' SIZE 128M AUTOEXTEND ON NEXT 50M MAXSIZE UNLIMITED
TABLESPACE GROUP ''
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1M;


DROP USER Support CASCADE;

CREATE USER Support
  IDENTIFIED BY 123
  DEFAULT TABLESPACE Support_DATA
  TEMPORARY TABLESPACE Support_TMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 3 Roles  
  GRANT CONNECT TO Support WITH ADMIN OPTION;
  GRANT RESOURCE TO Support WITH ADMIN OPTION;
  GRANT DBA TO Support WITH ADMIN OPTION;
  ALTER USER Support DEFAULT ROLE ALL;
  -- 2 System Privileges  
  GRANT ALTER TABLESPACE TO Support WITH ADMIN OPTION;
  GRANT UNLIMITED TABLESPACE TO Support WITH ADMIN OPTION;
