package Support;
/**
 * Generated by the Oracle9i JDeveloper Web Services Interface Generator
 * Date Created: Thu Sep 21 15:09:29 AST 2006
 * 
 * This interface lists the subset of public methods that you
 * selected for inclusion in your web service's public interface.
 * It is referenced in the web.xml deployment descriptor for this service.
 * 
 * This file should not be edited.
 */

public interface IMailSender 
{
  public void sendMail(String from, String[] to, String[] cc, String subject, String Body) throws Exception;
}